---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
  labels:
    app: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - name: books-ms
          image: sitolorenzoweb/books:1.0-SNAPSHOT
          ports:
            - containerPort: 8102
          volumeMounts:
            - mountPath: /app/config
              readOnly: true
              name: books-conf
      volumes:
        - name: books-conf
          configMap:
            name: books-conf
            items:
              - key: application.properties
                path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: books-service
  labels:
    app: books
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 32102
      port: 8102
      targetPort: 8102
  selector:
    app: books
---
apiVersion: v1
kind: ConfigMap
data:
  application.properties: |-
    #Local MongoDB config
    spring.data.mongodb.authentication-database=admin
    spring.data.mongodb.username=root
    spring.data.mongodb.password=root
    spring.data.mongodb.database=books_db
    spring.data.mongodb.port=27017
    spring.data.mongodb.host=books-mongodb

    # App config
    server.port=8102
    spring.application.name=BooksMicroservice
    server.servlet.context-path=/books-service

    # Log config
    logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE

    # Management config
    management.endpoint.info.enabled=true
    management.security.enabled=false
metadata:
  name: books-conf
  namespace: default
