version: "3.7"
services:

  books-ms:
    build:
      context: .
      args:
        MVN_ARGS: -DskipTests=true
    container_name: books-ms
    ports:
      - "8102:8102"
    depends_on:
      - mongodb_db

  mongodb_db:
    image: mongo:latest
    container_name: books-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: books_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: {}
